user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log warn;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
    multi_accept on;
    use epoll;
}

stream {
        # AdGuard Home intern, DoT-Port
        include /etc/nginx/stream.d/*.conf;
}


http {
    resolver 192.168.1.28 9.9.9.9 [fdf5:a5cc:270:0:be24:11ff:fecd:5693] valid=60s;
    resolver_timeout 2s;

    # rate limiting 
    # increase rate because of ipv6 testing
    limit_req_zone $binary_remote_addr zone=bw:80m rate=30r/s;
    limit_req_zone $binary_remote_addr zone=doh_limit:16m rate=80r/s; 
    limit_conn_zone $binary_remote_addr zone=doh_conn:16m;


    # QUIC-Debug aktivieren
    error_log /var/log/nginx/quick-error.log warn;

    # QUIC-Parameter optimieren
    quic_retry on;
    quic_gso on;  # falls verfügbar

    ##
    # Basic Settings
    ##

    ## Waf
    include /etc/nginx/waf/nginx/map/waf_maps.conf;

    sendfile on;
    tcp_nopush on;  # Kann aktiviert werden, je nach Bedarf
    types_hash_max_size 2048;
    server_tokens off;  # Verhindert das Senden der Nginx-Version in den HTTP-Headern

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1.3;  # TLSv1.2 und TLSv1.1 entfernen
    ssl_prefer_server_ciphers on;

    ##
    # Logging Settings
    ##

map $http_user_agent $loggable {
    ~*pulse-host-agent    0;
    ~*pulse-docker-agent  0;
    default               1;
}


log_format json_loki escape=json '{'
    '"time": "$time_iso8601", '
    '"remote_addr": "$remote_addr", '
    '"status": "$status", '
    '"request": "$request", '
    '"request_time": "$request_time", '
    '"http_referrer": "$http_referer", '
    '"http_user_agent": "$http_user_agent"'
'}';
    access_log /var/log/nginx/access.log json_loki;

    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 9;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    ##
    # Virtual Host Configsdns
    ##
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    client_max_body_size 200M;  # Falls du große Dateien hochladen möchtest

}
