rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
            push rtmp://127.0.0.1/hls;  # Stream an HLS-Application weiterleiten
        }

        application hls {
            live on;
            hls on;
            hls_path /mnt/hls/;  # Speicherort für HLS-Dateien
            hls_fragment 3s;  # Länge der HLS-Segmente
        }
    }
}
