[Interface]
Address = 10.0.0.1/24, fd00:cafe:1::1/64 
PrivateKey = [...]
ListenPort = 51820
# lokaler DNS Server
DNS = 192.168.1.28
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
#v6
PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
#v6
PostDown = ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -D FORWARD -o wg0 -j ACCEPT

#PostUp = echo "nameserver 192.168.1.28" > /etc/resolv.conf
#PostDown = echo "nameserver 192.168.1.28" > /etc/resolv.conf



# BW
[Peer]
PublicKey = 
AllowedIPs = 10.0.0.2/32, fd00:cafe:1::2/128
Endpoint = 192.168.178.118:51820
PersistentKeepalive = 25


# Paperless
[Peer]
PublicKey = 
AllowedIPs = 10.0.0.3/32, fd00:cafe:1::3/128
Endpoint = 192.168.3.20:51820
PersistentKeepalive = 25
