# Logging-Format für Stream (optional)
## nur für ein clinet stream -- keine unterscheidung von prod / test
log_format stream_logs '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time $upstream_addr '
                      'sni=$ssl_preread_server_name backend=$dot_backend';

# Rate-Limiting Zone
limit_conn_zone $binary_remote_addr zone=dot_conn_limit:30m;

# Upstream für AdGuard Home DoT
upstream dot_prod {
    server 192.168.2.20:1853;
}

# SNI-basiertes Routing (optional, hier nur eine Domain)
map $ssl_preread_server_name $dot_backend {
    doh.dns.xyz dot_prod;
    default dot_prod;
}

# Hauptserver für DoT auf Port 853
server {
    listen 853;

    # TLS SNI erkennen
    ssl_preread on;

    # Weiterleitung an AdGuard
    proxy_pass $dot_backend;

    # Rate-Limiting
    limit_conn dot_conn_limit 6;

    # Timeouts
    proxy_connect_timeout 5s;
    proxy_timeout 60s;
    proxy_responses 1;

    # Logging
#    access_log /var/log/nginx/dot_access.log;
    access_log /var/log/nginx/dot_prod_access.log stream_logs;
    error_log  /var/log/nginx/dot_error.log debug;

    # Proxy-Protocol
    proxy_protocol off;
}
