#Alle Upstreams + gemeinsames Mapping
# uebernimmt das post routing durch erkennen des ssi der domain welche auf den public port 853 zugreift
# nur eine dot config nötig weiter clients wuerden nachfolgend eingetragen werden

upstream dot_prod {
    server 192.168.2.20:853;
}

upstream dot_test {
    server 192.168.5.50:854;
}

map $ssl_preread_server_name $dot_backend {
    doh.dns.xyz dot_prod;
    doh.srv.xyz dot_test;
    default dot_prod;
}
