# Default catch-all Server (für alle unbekannten Domains)
## teseten mit -> curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0" http://localhost
## curl -I -A "Googlebot" http://localhost

map $http_user_agent $is_bot {
    default 0;
    ~*bot 1;
    ~*crawler 1;
    ~*spider 1;
    ~*scraper 1;
    ~*googlebot 1;
    ~*bingbot 1;
    ~*slurp 1;
    ~*duckduckbot 1;
    ~*facebookexternalhit 1;
    ~*twitterbot 1;
    ~*linkedinbot 1;
    ~*whatsapp 1;
    ~*telegram 1;
}

# 1. Default HTTP Server
server {
    listen 80 default_server;
    server_name _;
    if ($is_bot) {
        rewrite ^(.*)$ /loop/ permanent;
  
  # Optional: Logging
    access_log /var/log/nginx/default-acces.log;
    error_log /var/log/nginx/default-error.log;

    }

    location /loop/ {
        rewrite ^(.*)$ $1/loop/ permanent;
        error_page 500 =301 https://speed.hetzner.de/10GB.bin;
    }

    location / {
        return 301 http://0.0.0.0;
    }
#    return 444; 
#}

# 2. Default HTTPS Server
server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate  /var/lib/acme/doh.dns.ipv64.de.crt;
    ssl_certificate_key  /var/lib/acme/doh.dns.ipv64.de.key;

  # Optional: Logging
    access_log /var/log/nginx/default-acces.log;
    error_log /var/log/nginx/default-error.log;

    if ($is_bot) {
        rewrite ^ /loop$request_uri permanent;
    }

    location /loop {
        rewrite ^(.*)$ $1/loop permanent;
    }

    error_page 500 =301 https://speed.hetzner.de/10GB.bin;

    location / {
        return 301 http://0.0.0.0;
    }
#    return 444;
}
