upstream vaultwarden-default {
    server 10.0.0.2:8080;
    server [fd00:cafe:1::2]:8080;
    keepalive 32;
}

server {
    if ($host = bitwarden.my-domain.xyz) {
        return 301 https://$host$request_uri;
    } 

## upstream schnittstelle vlan 1
    listen 192.168.1.55:80;
    listen [fdf5:a5cc:270:0:be24:11ff:fe8a:bdf4]:80;
    server_name bitwarden.my-domain.xyz;
    location / {
        return 301 https://$host$request_uri;
    }
}

## upstream schnittstelle vlan 1
server {
    listen 192.168.1.55:443 ssl;
    listen [fdf5:a5cc:270:0:be24:11ff:fe8a:bdf4]:443 ssl;
    listen 192.168.1.55:443 quic reuseport;
    listen [fdf5:a5cc:270:0:be24:11ff:fe8a:bdf4]:443 quic reuseport;
    http2 on;
    http3 on;

    server_name bitwarden.dns.ipv64.de;
 
    ssl_certificate /etc/letsencrypt/live/bitwarden.my-domain.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bitwarden.my-domain.xyz/privkey.pem; # managed by Certbot

# SSL/TLS Modern Configuration
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;
#neu
    ssl_ecdh_curve X25519MLKEM768:X25519:prime256v1:secp384r1;

    add_header Alt-Svc 'h3=":443"; ma=86400' always;
    quic_retry on;
    
    location / {
        # falls das Backend auf 10.0.0.2:443 läuft, muss https genutzht werden
        proxy_pass http://vaultwarden-default;

# Falls das Backend ein selbstsigniertes Zertifikat nutzt,
# muss die Verifizierung hier abgeschaltet werden:
       # proxy_ssl_verify off;
       # proxy_ssl_server_name on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

# WebSocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

# Standard Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    }

    location /admin {
        deny all;
    }

# Access List (Example)
    allow 1.2.3.4; # DYN_IP
    allow 2a02:3100::[MAC-Adress]; # DYN_IP_V6
    deny all;

# Optional: Logging
    access_log /var/log/nginx/bitwarden.my-domain.xyz.access.log;
    error_log /var/log/nginx/bitwarden.my-domain.xyz.log debug;
}
