# The `upstream` directives ensure that you have a http/1.1 connection
# This enables the keepalive option and better performance
#
# Define the server IP and ports here.
## upstream ist bitwarden default

upstream vaultwarden-default {
  zone vaultwarden-default 64k;
  server 192.168.1.82:8080;
  keepalive 2;
}
### ab hier normale config
server {
    # Redirect HTTP to HTTPS
    listen 8080;
    server_name bitwarden.my-domain.xyz;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
# HTTPS Configuration
    listen 443 ssl;
    http2 on;
#    listen [::]:443 ssl;
 
    server_name bitwarden.dns.ipv64.de;
    ssl_certificate /var/lib/acme/bitwarden.my-domain.xyz.crt;
    ssl_certificate_key /var/lib/acme/bitwarden.my-domain.xyz.key;    
   

# Specify the protocols including QUIC and HTTP/3
    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1:secp384r1;
    ssl_prefer_server_ciphers on;
    client_max_body_size 525M;

# Add Alt-Svc header to advertise HTTP/3 support to clients
    add_header Alt-Svc 'h3-23=":443"'; # Note: 'h3-23' denotes the draft version and may change

# OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 127.0.0.1;  # optional anpassen auf externen dns server
    
# Reverse Proxy Settings
    location / {
        proxy_pass http://192.168.1.82:8080; # Replace with local server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
 
      #HTST
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
      # WebSocket Support (optional, if needed)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        location /admin {
        deny all;
    }

#Acces list
#        allow all;
#       allow 2002:bc65:1e8c:8000:9a9b:cbff:fec4:b046/128;
        allow 10.0.0.0/24;
        deny all;
    }

# Optional: Logging
    access_log /var/log/nginx/bitwarden.my-domain.xyz.access.log;
    error_log /var/log/nginx/bitwarden.my-domain.xyz.error.log;
}
