upstream backend_server {
    server 10.0.0.3:443;
    server [fd00:cafe:1::3]:443;
    keepalive 32;
}


server {
    listen 443 ssl;
    server_name paperless.home;
#    include /etc/nginx/waf/nginx/actions/waf_rules.conf;

    # SSL Certificate Paths
    ssl_certificate /etc/nginx/ssl/paperless.home.crt;
    ssl_certificate_key /etc/nginx/ssl/paperless.home.key;

    # Strong SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 100M;
    # Reverse Proxy Settings
    location / {
#       proxy_pass http://192.168.178.80:80; # Replace with local server
#        proxy_pass https://10.0.0.3:443; # Replace with local server        
        proxy_pass https://backend_server;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        
        # Ihre bestehenden Header beibehalten
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

# WebSocket Support (optional, if needed)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }


    # Optional: Logging
    access_log /var/log/nginx/paperless.home.access.log;
    error_log /var/log/nginx/paperless.home.error.log;
}

server {
    listen 80;
    server_name paperless.home;

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
