# 1. HTTP zu HTTPS Redirect (Standardmäßig auf Port 80)
server {
    listen 80; 
    server_name local.dns.ipv64.de;

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. Der eigentliche HTTPS Proxy
server {
    listen 443 ssl;
    http2 on;
    server_name local.dns.ipv64.de;

    # Zertifikatspfade
    ssl_certificate /var/lib/acme/local.dns.ipv64.de.crt;
    ssl_certificate_key /var/lib/acme/local.dns.ipv64.de.key;

    # Access List (Gilt für den gesamten Server-Block)
    allow 178.10.247.218;
    allow 10.0.0.0/24;
    allow 192.168.1.0/24;
    allow 192.168.178.0/24;
    allow 178.9.187.164;
    deny all;


    location / {
        # ZIEL: Wenn dein Dienst auf 5.10 auf Port 1411 hört
        proxy_pass http://192.168.5.10:1411;

        # Header-Weitergabe
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
