## pruefen der nginx funktion
server {
    listen 80;
    server_name 192.168.1.55;

    location /nginx_status {
        stub_status on;
        allow 192.168.5.6;  # oder deine Uptime-Kuma-IP
#        allow 88.71.68.83;
        deny all;
    }
}
