## pruefen der nginx funktion
server {
    listen 192.168.3.10:80;
    server_name 192.168.3.10;

    location /nginx_status {
        stub_status on;
        allow 192.168.5.6;  # oder deine Uptime-Kuma-IP
        deny all;
    }
}
