upstream vaultwarden-default {
    server 10.0.0.2:8080;
    server [fd00:cafe:1::2]:8080;
    keepalive 32;
}

server {
    listen 80;
    server_name bitwarden.my-domain.xyz;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen 443 quic reuseport;
    http2 on;
    http3 on;

    server_name bitwarden.my-domain.xyz;
    ssl_certificate /var/lib/acme/bitwarden.my-domain.xyz.crt;
    ssl_certificate_key /var/lib/acme/bitwarden.my-domain.xyz.key;


    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        # WICHTIG: wenn Backend auf 10.0.0.2:443 läuft, wird https genutzt
        proxy_pass http://vaultwarden-default;

       # Falls das Backend ein selbstsigniertes Zertifikat nutzt
       # proxy_ssl_verify off;
       # proxy_ssl_server_name on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Standard Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    }

    location /admin {
        deny all;
    }

    # Access List
#    allow all; # debug
    allow 10.0.0.0/24;
    allow [public ip];
    deny all;

    # Optional: Logging
    access_log /var/log/nginx/bitwarden.my-domain.xyz.access.log;
    error_log /var/log/nginx/bitwarden.my-domain.xyz.error.log;

}
